### ISSUE TITLE
First nested item does not expand in a deeply nested model structure using Grapelli

### ISSUE THREAD

**Issue by riwart** [theatlantic/django-nested-admin#122]
I'm having trouble with the nested admin when trying to expand (mouse-click) the first collapsed sub-item of a NestedStackedInline item using the grappelli interface: It won't expand. When I click "add another", the newly added item can be expanded, but the first item still can't be expanded. This is highly unfortunate, because when I try to save the entire nested model (NestedModelAdmin) like this, my field validation raises numerous errors as it tries to save a some model without any data.

I am using a rather deeply nested structure with three NestedStackedInline items below the superior NestedModelAdmin, each (except the last) representing a 1:m relation: NestedModelAdmin - NestedStackedInline1 - NestedStackedInline2 - NestedStackedInline3. Strangely, the issue in the admin only occurs when trying to expand an item belonging to either NestedStackedInline2 or NestedStackedInline3 - no problem with NestedStackedInline1. And to complicate things further, the issue only occurs for the second/third/... item of NestedStackedInline1; for the first one, everything works fine.

What I have further observed is that, when an item can not be expanded and I click it several times, sometimes it appears as if it tries to expand (for a few microseconds) but then immediately it collapses again.

On the frontend, the HTML code only differs with respect to the order of the css classes that are assigned to the <div> elements containing the collapsed NestedstackedInline. This one can not be expanded (div classes do not change):
<div class="djn-item grp-module djn-module djn-inline-form grp-collapse grp-closed  inline-related dynamic-form grp-dynamic-form djn-dynamic-form-myproject-mynestedmodel2" data-is-initial="false" id="mynestedmodel1_set-1-mynestedmodel2_set-0" style="display: block;">
... while this one can be expanded:
<div class="grp-module djn-module djn-inline-form grp-collapse  inline-related djn-item dynamic-form grp-dynamic-form djn-dynamic-form-myproject-mynestedmodel2 grp-closed" data-is-initial="false" id="mynestedmodel1_set-1-mynestedmodel2_set-1" style="display: block;">
This one can also be expanded:
<div class="djn-item grp-module djn-module djn-inline-form grp-collapse  inline-related dynamic-form grp-dynamic-form djn-dynamic-form-myproject-mynestedmodel2 grp-closed" data-is-initial="false" id="mynestedmodel1_set-0-mynestedmodel2_set-0" style="">

However, as far as I know the order of css class attributes can be completely arbitrary?

This is the list of relevant packages I'm using:
Django==2.0.10
django-grappelli==2.12.2
django-nested-admin==3.1.3

I have tried with both Firefox Quantum 60.5.0esr (64-bit) and with Chrome, same issue.

I hope you can reproduce this issue, as it is quite specific to my setup (I assume). It'd be great if this could be solved sooner or later... Thank you in advance!

**Comment by riwart** [comment]
I have just updated to Python 3.6.8 and Django 2.1.5, still the issue remains.

**Comment by fdintino** [comment]
Could you see if this is still an issue in the nested admin 3.2.0 release?

**Comment by riwart** [comment]
Thanks for the new release. I have updated to 3.2.1 and also updated to Django 2.2, but the issue remains. I would be very happy if this issue could be resolved quite soon... To help you with this I will create a dummy project with a very simple model structure and try to reproduce the issue.

**Comment by riwart** [comment]
I have now set up a test system with minimal package requirements:
```
Django==2.2
django-grappelli==2.12.2
django-nested-admin==3.2.1
```

These are my installed apps (in settings.py):
```
INSTALLED_APPS = [    
    'django.contrib.auth',
    'django.contrib.contenttypes',    
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nested_admin',
    'grappelli',
    'django.contrib.admin',
    'test_app',
]
```
Note that I have put 'django.contrib.admin' after 'grappelli' and 'nested_admin'; otherwise the static files are not loaded which is totally messing up the admin interface. The order of grappelli with respect to nested-admin seems to make no difference.

My urls.py:
```
from django.contrib import admin
from django.urls import path, include

urlpatterns = [        
    path('nested-admin/', include('nested_admin.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]
```

My models.py:
```
from django.db import models

class Parent(models.Model):
	name = models.CharField(max_length=10)
	def __str__(self):
		return self.name

class Child1(models.Model):
	name = models.CharField(max_length=10)
	parent = models.ForeignKey(Parent, on_delete=models.SET_NULL, blank=True, null=True)
	def __str__(self):
		return self.name

class Child2(models.Model):
	name = models.CharField(max_length=10)
	child1 = models.ForeignKey(Child1, on_delete=models.SET_NULL, blank=True, null=True)
	def __str__(self):
		return self.name
```
Note that if I use only Parent and Child1, the problem in the admin never occurs.

My admin.py:
```
from .models import Parent, Child1, Child2
from django.contrib import admin
import nested_admin

class Child2Inline(nested_admin.NestedStackedInline):
	model = Child2
	extra = 0
	min_num = 1

class Child1Inline(nested_admin.NestedStackedInline):
	model = Child1
	inlines = [Child2Inline]
	extra = 0
	min_num = 1

class ParentAdmin(nested_admin.NestedModelAdmin):
	model = Parent
	inlines = [Child1Inline]
	extra = 0
	min_num = 1

admin.site.register(Parent, ParentAdmin)
```
Then if I go to my admin interface, I can add a first instance of Parent/Child1/Child2 without further problems. But if I want to add another Child1 item, its Child2 item does not expand if I click on it. If I add a second Child2 item, this second item can be expanded, while the first one still won't expand. Very strange...

I figured out that if I set min_num in Child1Inline and Child2Inline to 0, my problem suddenly disappears. But this is not very user friendly, because (in my case) for each Parent at least one instance of Child1 and at least one instance of Child2 must exist.

I can put my test project on gitlab if that helps you.

Thanks for your contributions!!
Richard

**Comment by fdintino** [comment]
Thanks so much for the detailed information! It was enough for me to write a test, which really helped work out the fix. Could you check against the branch `pr/fix-issue-122` and see if this resolves your issue?

**Comment by riwart** [comment]
I am afraid it is still not working. I uninstalled and re-installed via
`pip install git+https://github.com/theatlantic/django-nested-admin@pr/fix-issue-122`
... but the issue remains. When I know click on the nested item that does not want to expand, I can see some flickering, as if it is trying to expand. Maybe there is some other javascript or css rule preventing it from opening?

**Comment by fdintino** [comment]
That's strange, because I reproduced your test case exactly, observed that the bug existed, and made the change to fix it. Could there be an additional condition in your code that isn't represented in that test case? Or do you observe the problem even with the code you posted?

**Comment by fdintino** [comment]
I do have one last theory remaining, which is that the collapse handler is being registered twice, hence the flickering (the first handler opens it, the second one collapses it). But that doesn't happen with the minimal test case, so it would be good to know how I can test the conditions that produce that bug.

**Comment by fdintino** [comment]
I found an issue I could reproduce that I suspect is related to your problem, so I pushed out a test and a fix for it on the branch. Could you update your package to the latest commit on `pr/fix-issue-122` and give it another shot?

**Comment by riwart** [comment]
Hi Frankie

unfortunately the bug still won't disappear. I do observe the problem even with the code I have posted above. I have created a temporary git repository for it, so you can reproduce the issue: 
https://github.com/riwart/django-nested-admin-test

Hope that helps...
Richard

**Comment by fdintino** [comment]
I think you might not have the correct branch checked out and enabled. I started fresh, but edited your requirements.txt so it had this for django-nested-admin:

```
-e git+git@github.com:theatlantic/django-nested-admin.git@pr/fix-issue-122#egg=django-nested-admin
```

Here's a video I took of the admin interface: 

https://www.frankiedintino.com/static/misc/django-nested-admin-test-demo.mp4

**Comment by fdintino** [comment]
I'm going to go ahead and merge this work (because it does fix several bugs, though I'd need confirmation that it fixes yours specifically). Merging might auto-close this ticket, but please reopen if you can confirm that there is still a bug remaining.
