### ISSUE TITLE
Fix adding ForeignKey instance to inline model

### ISSUE THREAD

**Issue by vivazzi** [theatlantic/django-nested-admin#45]
Many thanks for great app for the createing of nested inlines!

I use Django==1.8.4 and now I get some bugs with the adding of ForeignKey values in inline model. Whan I add another inline object I cannot add new foreign key item (only select and change selected item). For test may use follow models:
```
# models.py
class OtherModel(models.Model):
    field = models.CharField(max_length=4)

class Main(models.Model):
    field = models.CharField(max_length=4)

class Level1(models.Model):
    field = models.CharField(max_length=4)
    other_model = models.ForeignKey(OtherModel, null=True, blank=True)
    main = models.ForeignKey(Main)

class Level2(models.Model):
    field = models.CharField(max_length=4)
    level_1 = models.ForeignKey(Level1)

# admin.py
@admin.register(OtherModel)
class OtherModelAdmin(admin.ModelAdmin):
    pass

class Level2Inline(NestedTabularInline):
    model = Level2
    extra = 0

class Level1Inline(NestedStackedInline):
    model = Level1
    inlines = (Level2Inline, )
    extra = 0

@admin.register(Main)
class MainAdmin(NestedModelAdmin):
    inlines = (Level1Inline, )

@admin.register(Level1)
class Level1Admin(admin.ModelAdmin):
    pass

@admin.register(Level2)
class Level2Admin(admin.ModelAdmin):
    pass
```

And if I click "Add another Level1" and click add OtherModel instance (I marked with red border):
![test](https://cloud.githubusercontent.com/assets/11954799/15849616/0eb902ec-2cc6-11e6-88c5-d1804eb058ff.png)
then It is no effect. Field "Other model" is empty (without created other model instance).

P. S. In my screen I used djangocms_admin_style fro pretty admin view, but also there is a bug without djangocms_admin_style when I tested.

**Comment by fdintino** [comment]
This is fixed in the 3.0.5 release.

**Comment by vivazzi** [comment]
Thanks for fix. But It seems bug is not completely fixed. I use django-easy-select2 for autocomplete for other_model = models.ForeignKey(OtherModel, null=True, blank=True) (if see my example). I tested django-easy-select2 without django-nested-admin and it work. But with django-nested-admin when I click "Add another Level1" then I get no render select2 widget for "Other Model". 
![test](https://cloud.githubusercontent.com/assets/11954799/15887082/cf52022a-2d92-11e6-8366-6af0c717be2b.png)

**Comment by fdintino** [comment]
That would be a separate issue. Could you try adding javascript like this to some javascript in your project included in the admin?

```javascript
(function($) {
    $(document).ready(function() {
        $(document).on('formset:added', function(event, $form) {
            $form.find('div.field-easy-select2:not([id*="__prefix__"])').each(function() {
                var $el = $(this);
                $("#" + $el.attr('id')).on('select2changed', function() {
                    $($(this)).select2($el.data());
                }).trigger('select2changed');

                $el.remove();
            });
        });
    })
})(window.jQuery || django.jQuery);
```

I haven't tested it, but something like that might work.

**Comment by vivazzi** [comment]
Unfortunately, this code doesn't work for me. Maybe I don't correct include js. Usually I add like that:
```
class Level1Form(forms.ModelForm):
    class Meta:
        exclude = ()
        widgets = {
            'other_model': Select2(),
        }

    class Media:
        js = ['spec/fix_select2.js', ]
```
where fix_select2 is your code.
